### ISSUE TITLE
Is it possible to chat with gpt after summarize? 

### ISSUE THREAD

**Issue by SkMunna505** [sparticleinc/chatgpt-google-summary-extension#102]
Something we need to asked some additional information to understand completely some topics.
I would like to be able to chat with GPT to ask questions about the summary or to add additional information.

**Comment by givebest** [comment]
Recent new releases include this feature.
<img width="1162" alt="page-qa" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/df0f26b1-5d33-43a6-a4be-ce74dbc47bfe">

**Comment by SkMunna505** [comment]
> SkMunna505

![IMG_20230518_070922](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/133928119/98c17666-01ad-433b-a94d-7a3246647b0f)
Downloaded from chrome store (V 1.15.1)
Still same so chat option 😔
Can you please provide me the link of the latest file

**Comment by givebest** [comment]
The Beta version can be experienced here: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages

**Comment by SkMunna505** [comment]
> The Beta version can be experienced here: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages

Thank you so much for your help.Your quick response and solution were greatly appreciated.

I really appreciate your work on this project. It's clear that you put a lot of time and effort into making it a great resource for everyone.🔥

Thanks again for your help!💙

**Comment by SkMunna505** [comment]
Feature added on beta version

**Comment by SkMunna505** [comment]
Thank you so much for your help.Your quick response and solution were greatly appreciated.

I really appreciate your work on this project. It's clear that you put a lot of time and effort into making it a great resource for everyone.🔥

Thanks again for your help!💙
