### ISSUE TITLE
ask doesnt respect API Host settings

### ISSUE THREAD

**Issue by ken-wizhodl** [sparticleinc/chatgpt-google-summary-extension#103]
Ask feature send requests to api.openai.com instead of the API host in the settings.

- OS: [MacOS]
- Browser [chrome]
- Version [v2.0.0]

**Comment by givebest** [comment]
Try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages

**Comment by ken-wizhodl** [comment]
V2.1.0 as the latest package you give me, it still doesn't work, embedding requests still goes to api.openai.com .

**Comment by givebest** [comment]
We tried again and it worked.
<img width="1100" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/f896bb96-a058-4ec3-8607-d8e415626622">

**Comment by ken-wizhodl** [comment]
Thanks, it worked after I re-enabled the extension.
