### ISSUE TITLE
Ask wrong completion path

### ISSUE THREAD

**Issue by ken-wizhodl** [sparticleinc/chatgpt-google-summary-extension#104]
Ask feature use https://api.myhost.com/v1/completions instead of https://api.myhost.com/v1/chat/completions.

Please note I setted API host.

- OS: [MacOS]
- Browser [chrome]
- Version [v2.1.0]

**Comment by givebest** [comment]
Is there any advantage to using `/v1/chat/completions` in the Q&A?
