### ISSUE TITLE
"Copy" button for Q&A

### ISSUE THREAD

**Issue by rkakamilan** [sparticleinc/chatgpt-google-summary-extension#108]
I like the copy button for default features, "summary", "Q&A" and so on. But it is not possible for custom qustions and answers. It would be great if there is a button/feature to copy the custom q/a as well.

**Comment by givebest** [comment]
Try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/main/packages/Glarity-chromium-beta.zip

**Comment by rkakamilan** [comment]
Thanks for sharing the code and I apologize for the delayed response. I tried it and could copy the answer. This is a great update, but it would be even better if I could copy not just the answer but the entire thread of Q&A. Would it be possible to include this feature in the next update?

**Comment by givebest** [comment]
This is a good suggestion and we plan to add it.
