### ISSUE TITLE
Feature Request: Add Separated Toggles for Supported Websites

### ISSUE THREAD

**Issue by tastysugar** [sparticleinc/chatgpt-google-summary-extension#11]
**Describe the Issue**
After a few days of usage, I really like the extension when it summarizes a YouTube video. But I don't want it to show up every time I use Google search. 
Is it possible to add a feature that allows the user to toggle on or off the extension for each supported website?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by givebest** [comment]
Maybe you need to try setting manual mode in Options.

**Comment by tastysugar** [comment]
I actually prefer it to summarize some websites (namely YouTube) automatically, without pressing the button. But I do not want it to show up in Google Search result. 

Is this a reasonable request to consider?

I meant, I use Google search **a lot**. And I am not a novice Google search user. I know where to find the information I need.
The manual mode is an good enough solution for making the dialog to not show up in Google search. But the side effect is that I have to press a button to enable it on other websites that I actually need it.

**Comment by givebest** [comment]
Understood, follow up with a site switch option.
