### ISSUE TITLE
是否可以加入对Azure openai service的支持

### ISSUE THREAD

**Issue by diaohonghui** [sparticleinc/chatgpt-google-summary-extension#111]
新功能 | New Feature
支持Azure openai service，可以使用Azure的终结点与api key访问gpt

为什么您想要添加这些功能 | Why you want to add these features
因为openai的key在无代理的情况下使用风险较大，而azure不会

**Comment by givebest** [comment]
试下这里：https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/main/packages/Glarity-chromium-beta.zip

**Comment by diaohonghui** [comment]
总是会提示找不到resource，看了一下endpoint处会自动将http吞掉，不知道是不是这个问题导致的
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/19686851/340b6ae6-2162-445e-a9f0-f39177ae45c8)

**Comment by givebest** [comment]
代码里面会加上https，试下Chrome 扩展商店2.3版本，我们测试是可以的。
