### ISSUE TITLE
The extension is making code blocks on every website unreadable, like corrupted

### ISSUE THREAD

**Issue by april-computers** [sparticleinc/chatgpt-google-summary-extension#112]
**The extension is making code blocks on every website unreadable, like corrupted**
 When the extension is enabled:
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/109056292/c5685ac7-f0f5-48f3-8a6b-0f8cd3997534)

But when it is disabled:
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/109056292/ba4af88c-4b3a-4dfe-a343-a3997698d596)

**Comment by h3y6e** [comment]
Hello,
I'm also having the same issue. My browser is Firefox Developer Edition version 114.0b9. 
I've found that disabling the Glarity extension resolves the problem. 

Thanks.

**Comment by boholder** [comment]
Maybe relative to this: 

https://github.com/openai-translator/openai-translator/pull/780

**Comment by givebest** [comment]
Try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/main/packages/Glarity-chromium-beta.zip

<img width="835" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/d2a0405a-21c4-41e0-9b77-2c0bd78eadfd">
