### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by mehrdadsobouti** [sparticleinc/chatgpt-google-summary-extension#113]
Is there anyone help me with this error?

Failed to load response: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

windows
chrome

**Comment by givebest** [comment]
It looks like the openAI API quota is running out.

**Comment by mehrdadsobouti** [comment]
but I don't use it that much!

**Comment by givebest** [comment]
The openAI API quota has a time limit.

**Comment by mehrdadsobouti** [comment]
Thank you for clarifying.
