### ISSUE TITLE
Add suppor for the new gpt models. 16k context lenght.

### ISSUE THREAD

**Issue by ioma8** [sparticleinc/chatgpt-google-summary-extension#122]
**Describe the bug**
OpenAI just rececently released new 3.5 models. One of them is gpt-3.5-turbo-16k which supports 16k tokens context lengths. Add support for this model please.

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- Version [e.g. 1.15.1]

**Comment by ioma8** [comment]
I have made a PR for this issue: https://github.com/sparticleinc/chatgpt-google-summary-extension/pull/123

**Comment by givebest** [comment]
Thank you very much, I have merged.
