### ISSUE TITLE
Not working with openai api key

### ISSUE THREAD

**Issue by camillebernier** [sparticleinc/chatgpt-google-summary-extension#132]
**Describe the bug**
It is not working with any model if I put an openai api key. I got this error :
```
Failed to load response: {"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}
```

Same error with the other models.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser : Firefox 114.0.2
- Version : 2.5.7

**Comment by givebest** [comment]
Try going to the options and selecting the turbo3.5 model.

**Comment by givebest** [comment]
This error indicates that the OpenAI API fee has run out, try selecting ChatGPT WebApp in options.
