### ISSUE TITLE
Youtube Whisperer errors with "OSError: All ports from 7860 to 7860 are in use. Please close a port."

### ISSUE THREAD

**Issue by jonathanhawleypeters** [sparticleinc/chatgpt-google-summary-extension#146]
**Describe the bug**
Try [Youtube Whisperer](https://huggingface.co/spaces/jeffistyping/Youtube-Whisperer) to transcribe! errors with a message about a port in use.

**Desktop (please complete the following information):**

- OS: macOS Monterey version 12.4
- Browser Safari
- Version [(v1.16.0)](https://glarity.app/)

- Logs

Runtime error
Space failed. Exit code: 1. Reason:                              | 11.6M/139M [00:00<00:01, 121MiB/s]
 18%|███████▏                               | 25.4M/139M [00:00<00:00, 135MiB/s]
 28%|██████████▊                            | 38.2M/139M [00:00<00:00, 134MiB/s]
 37%|██████████████▍                        | 51.2M/139M [00:00<00:00, 135MiB/s]
 46%|██████████████████                     | 64.3M/139M [00:00<00:00, 136MiB/s]
 58%|██████████████████████▍                | 79.8M/139M [00:00<00:00, 145MiB/s]
 68%|██████████████████████████▎            | 93.6M/139M [00:00<00:00, 143MiB/s]
 77%|██████████████████████████████▉         | 107M/139M [00:00<00:00, 141MiB/s]
 87%|██████████████████████████████████▊     | 121M/139M [00:00<00:00, 141MiB/s]
 97%|██████████████████████████████████████▋ | 134M/139M [00:01<00:00, 141MiB/s]
100%|████████████████████████████████████████| 139M/139M [00:01<00:00, 139MiB/s]
Traceback (most recent call last):
  File "/home/user/app/app.py", line 93, in <module>
    block.launch()
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 1040, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/networking.py", line 115, in start_server
    port = get_first_available_port(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/networking.py", line 66, in get_first_available_port
    raise OSError(
OSError: All ports from 7860 to 7860 are in use. Please close a port.
Container logs:

===== Application Startup at 2023-08-04 00:22:18 =====

  0%|                                               | 0.00/139M [00:00<?, ?iB/s]
  9%|███▍                                   | 12.3M/139M [00:00<00:01, 129MiB/s]
 18%|██████▉                                | 24.6M/139M [00:00<00:01, 116MiB/s]
 27%|██████████▎                            | 36.8M/139M [00:00<00:00, 120MiB/s]
 35%|█████████████▊                         | 49.1M/139M [00:00<00:00, 124MiB/s]
 44%|█████████████████▎                     | 61.6M/139M [00:00<00:00, 126MiB/s]
 54%|████████████████████▉                  | 74.3M/139M [00:00<00:00, 128MiB/s]
 63%|████████████████████████▍              | 87.0M/139M [00:00<00:00, 130MiB/s]
 72%|███████████████████████████▉           | 99.4M/139M [00:00<00:00, 130MiB/s]
 81%|████████████████████████████████▎       | 112M/139M [00:00<00:00, 130MiB/s]
 90%|███████████████████████████████████▉    | 124M/139M [00:01<00:00, 126MiB/s]
 99%|███████████████████████████████████████▍| 137M/139M [00:01<00:00, 125MiB/s]
100%|████████████████████████████████████████| 139M/139M [00:01<00:00, 126MiB/s]
Traceback (most recent call last):
  File "/home/user/app/app.py", line 93, in <module>
    block.launch()
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 1040, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/networking.py", line 115, in start_server
    port = get_first_available_port(
  File "/home/user/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/networking.py", line 66, in get_first_available_port
    raise OSError(
OSError: All ports from 7860 to 7860 are in use. Please close a port.

**Comment by givebest** [comment]
Thank you for your feedback, this is a third party service, please go here to feedback issues: https://huggingface.co/spaces/jeffistyping/Youtube-Whisperer/discussions.
