### ISSUE TITLE
在界面上重复出现

### ISSUE THREAD

**Issue by klefjkl** [sparticleinc/chatgpt-google-summary-extension#149]
**Describe the bug**
谷歌搜索后在界面中上下重复出现两个总结，见附图右边
**Desktop (please complete the following information):**

- OS: [e.g. Windows] win10
- Browser [e.g. chrome, brave] 最新chrome稳定
- Version [e.g. 1.15.1]最新
-[url=https://imgse.com/i/pP0gOwd][img]https://s1.ax1x.com/2023/09/01/pP0gOwd.md.png[/img][/url]
[![pP0gOwd.png](https://s1.ax1x.com/2023/09/01/pP0gOwd.png)](https://imgse.com/i/pP0gOwd)

**Comment by givebest** [comment]
Try the latest version 3.x。
试下使用最新版本3.x。
