### ISSUE TITLE
Summary: On Bilibili, the summarization feature is using page text content instead of subtitles or automatic captions.

### ISSUE THREAD

**Issue by Blazing5903** [sparticleinc/chatgpt-google-summary-extension#150]
**Describe the bug**
Summary: On Bilibili, the summarization feature is using page text content instead of subtitles or automatic captions.

**Desktop (please complete the following information):**

- OS: Windows
- Browser edge 116.0.1938.69
- Version 3.0.1

**Comment by givebest** [comment]
Please provide the video URL and we'll troubleshoot it.

**Comment by Blazing5903** [comment]
> Please provide the video URL and we'll troubleshoot it.

automatic captions
https://www.bilibili.com/video/BV1qE411h72m

subtitles
https://www.bilibili.com/video/BV15G411J7MN

**Comment by givebest** [comment]
<img width="474" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/9124d3f0-6853-46ec-823e-cd958ae89468">

I've read that there are no transcribed text subtitles for these two videos. Note: not the subtitles that come with the subtitles.

**Comment by Blazing5903** [comment]
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/3918120/265369630-9124d3f0-6853-46ec-823e-cd958ae89468.png">
> I've read that there are no transcribed text subtitles for these two videos. Note: not the subtitles that come with the subtitles.

I tested the case of logging out, and indeed there are no subtitles. The option to enable subtitles appears after logging in, so if needed, you can contact me to provide an account.
