### ISSUE TITLE
Blocks Asus router interface

### ISSUE THREAD

**Issue by ArmynC** [sparticleinc/chatgpt-google-summary-extension#152]
**Describe the bug**
When I try to configure my Asus rotuer, the menu isn't there. By disabling the extension, it reappears.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: 118.0b8 
- Extension: Glarity v2.7.8

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/16375271/de2ad524-2e33-483d-9035-785c0a9158e5)

**Comment by givebest** [comment]
Thanks for the feedback, try the latest version?

**Comment by ArmynC** [comment]
I think it is solved.
