### ISSUE TITLE
Glarity can't work properly in Kagi search

### ISSUE THREAD

**Issue by limfoo** [sparticleinc/chatgpt-google-summary-extension#154]
OS：Windows 11
Browser：Edge 117.0.2045.31
Glarity: V3.2

Issue: Glaity seems can't work properly in Kagi search, screenshot as below, I am not a developer so I can't provide further details, but please help to look into this issue. thanks in advance.

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/34062417/b86aa35f-cdd8-4355-8aa8-4ab54e6ed9e1)

**Comment by givebest** [comment]
Thanks for the feedback, we'll fix it for the next iteration.

**Comment by givebest** [comment]
This issue has been fixed in v3.39.
