### ISSUE TITLE
Feature Request: Support gpt 3.5 turbo and other model

### ISSUE THREAD

**Issue by superylc** [sparticleinc/chatgpt-google-summary-extension#16]
It looks like that I can only choose davinci-003 model.
Since 3.5 turbo is much cheaper, it's better to support new models.

**Comment by IlluminateDarkheat** [comment]
You need to download the latest version here.

https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/main/packages/Glarity-chromium.zip
