### ISSUE TITLE
Reddit shows duplicate messages with some kind of grammar correction if the extension is enabled

### ISSUE THREAD

**Issue by dariomorellidesign** [sparticleinc/chatgpt-google-summary-extension#160]
Browsing the reddit website, every paragraph of every message, and also some menu items, buttons etc. appears duplicated with some sort of grammar/syntax correction.

here some examples.

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/108741682/299f03d8-70f7-4e57-888a-d4a4d8215b3a)

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/108741682/5b44432d-aac6-4e57-bab4-1a6991541a3f)

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/108741682/e694b857-3f11-40fb-bab9-0899d85a9194)

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/108741682/ac836712-7190-4525-8fab-ee4500871341)

there is no option about it in the extension. it's very annoying and there's also no option to disable the extension on a website.

this is an example of an event log while refreshing a reddit page:
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/108741682/971cc8b2-372a-48b7-8e70-37fcfa299c55)

- OS: win10 pro
- Browser: chrome
- Version 111.0.5563.19 (Official Build) beta (64-bit) and Version 112.0.5615.138

**Comment by givebest** [comment]
May I ask what version of Glarity you are using? You can check it in Extension Options.

**Comment by dariomorellidesign** [comment]
> May I ask what version of Glarity you are using? You can check it in Extension Options.

v3.40.15

**Comment by givebest** [comment]
> > May I ask what version of Glarity you are using? You can check it in Extension Options.
> 
> v3.40.15

Thanks for the feedback, we've pinpointed the issue and plan to bring up a new version to fix it today.

**Comment by dariomorellidesign** [comment]
great! thank you very much!

**Comment by givebest** [comment]
Version 3.42 is fixed and can now be updated in the Chrome Store.
