### ISSUE TITLE
not working as of today for chatgpt web

### ISSUE THREAD

**Issue by GorvGoyl** [sparticleinc/chatgpt-google-summary-extension#161]
**Describe the bug**
the response generated is the same as the question. 

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Comment by givebest** [comment]
Thank you for your feedback, we are aware of this issue, it is due to a ChatGPT rule change and will be reviewing a release this week to fix it.

**Comment by givebest** [comment]
The fixed version is now available and can be updated for use in this [Chrome web store](https://chrome.google.com/webstore/detail/summary-for-google-with-c/cmnlolelipjlhfkhpohphpedmkfbobjc).
