### ISSUE TITLE
期望黑名单功能，能让插件直接在当前页面不生效

### ISSUE THREAD

**Issue by lazygoat644** [sparticleinc/chatgpt-google-summary-extension#164]
**Describe the bug**
在部分公司内网的网页开启该插件，会使得页面排版出现问题，升级前的旧版本没有这种问题。
由于数据敏感，当前无法直接展示截图，因此期望「黑名单」功能，可以直接自动使得该插件在该页面不生效，而不是通过人工开启/关闭插件的方式来实现效果。

**Desktop (please complete the following information):**

- OS: [e.g. Windows] macos 14.1
- Browser [e.g. chrome, brave] chrome 118.0.5993.117
- Version [e.g. 1.15.1] 3.44.15

**Comment by givebest** [comment]
抱歉这个网页排版问题是这个版本的 bug，上周已修复提审，升级后就没这个问题了。

**Comment by givebest** [comment]
麻烦更新到 3.45.11 可以解决这个问题。
