### ISSUE TITLE
隐藏图标后无法通过点击浏览器扩展图标来激活摘要功能

### ISSUE THREAD

**Issue by kooleelee** [sparticleinc/chatgpt-google-summary-extension#166]
**Describe the bug**
在页面上隐藏图标后，点击浏览器扩展图标无反映
显示图标后，在页面上点击图标，总结功能正常

**Desktop (please complete the following information):**

- OS: MacOS 14.1 
- Browser: Chrome 119.0.6045.105
- Version: 3.45.11

**Comment by ytqh** [comment]
有同样的问题，点击浏览器扩展图标无反映，我发唤出Summary Panel

- OS: MacOS 14.2.1
- Browser: Chromium 120.0.6099.129
- Version: 3.52.13

**Comment by givebest** [comment]
刷新下网页呢

**Comment by givebest** [comment]
根据您的反馈，建议尝试安装最新版本以解决该问题。如果问题仍然存在，请提供详细的复现步骤，以便我们更好地帮助您解决此问题。感谢您的理解与配合。
