### ISSUE TITLE
Styles Missing in Route Search on Baidu Maps with chatgpt-google-summary-extension

### ISSUE THREAD

**Issue by rootsongjc** [sparticleinc/chatgpt-google-summary-extension#171]
**Describe the bug**
I encountered a bug while using the [chatgpt-google-summary-extension](https://github.com/sparticleinc/chatgpt-google-summary-extension) Chrome extension. When I perform a route search on [Baidu Maps](https://map.baidu.com/), the styles for the displayed paths seem to be missing or incorrect. I'm using macOS with Chrome browser version 119.0.6045.159.

<img width="459" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3328185/bf96f684-7339-4dd2-9cbe-28cd0d31ff7e">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 119.0.6045.159

**Comment by chendotjs** [comment]
Encounter the same issue

**Comment by rootsongjc** [comment]
This problem not only appears on Baidu map, but also appears on many web pages, which is basically unusable.

**Comment by givebest** [comment]
Thanks for your feedback, the latest version has been fixed.

<img width="414" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/44a99477-011e-44a0-ac79-60133001e1ac">
