### ISSUE TITLE
侧边栏功能无法调用自定义api接口

### ISSUE THREAD

**Issue by wxy-skye** [sparticleinc/chatgpt-google-summary-extension#174]
<img width="366" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/87176224/87b8425d-31b9-4ef7-88eb-1b757a27fd63">
还是调用了openai的接口，没有访问到自定义的接口地址导致侧边栏无法使用

**Comment by learningdog1** [comment]
+1

**Comment by givebest** [comment]
感谢反馈，这周的新版修复。

**Comment by wxy-skye** [comment]
> 感谢反馈，这周的新版修复。

好像还是没修复  是我姿势不对吗？

**Comment by givebest** [comment]
> > 感谢反馈，这周的新版修复。
> 
> 好像还是没修复 是我姿势不对吗？

这周修复版本还没通过审核：）

**Comment by givebest** [comment]
新版已通过审核，麻烦更新一下。
