### ISSUE TITLE
Font Size in Chrome Sidebar

### ISSUE THREAD

**Issue by bobbyzhou** [sparticleinc/chatgpt-google-summary-extension#175]
Would appreciate if could let users customize the font size in Chrome Sidebar. Currently, font looks very small for Page Summary

**Comment by givebest** [comment]
Thanks for the feedback, this feature will be supported in the next release.

**Comment by givebest** [comment]
Thanks for the feedback, this feature will be supported in the next release.

**Comment by givebest** [comment]
Thanks for your feedback, we've fixed this issue in the latest version and now support user-defined font sizes for the Chrome sidebar.
