### ISSUE TITLE
Summary: On Bilibili, the summarization feature is using page text content instead of subtitles.

### ISSUE THREAD

**Issue by skQuat** [sparticleinc/chatgpt-google-summary-extension#179]
**Describe the bug**

Problem: On Bilibili, the summarization feature is using page text content instead of subtitles. I've noticed that someone has already raised this issue and marked it as completed months ago, but the problem has not yet been resolved. 

Example: The video in the picture below is particularly noticeable. It's a video that shares and ranks mystery novels in 2023, and the page content provides some hyperlink and description related to the author's previous videos. It can be seen that the summary is entirely related to the page content (each highlight includes the unique serial number of previous video like BV1pF411c7Zc , which only exits in the page content). 

Original Url: https://www.bilibili.com/video/BV1eT4y1s7Ww. It has been confirmed that there are Chinese subtitles.

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/33716136/bfc19545-89fc-485b-b1e6-b67c1e9c2d08)
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/33716136/e119f2b5-2662-4500-bbb3-42a7d968e4e5)

**Desktop (please complete the following information):**

- OS:          Windows
- Browser:  Edge 120.0.2210.91
- Version:   v3.52.13

**Comment by givebest** [comment]
Thanks for the feedback, we've removed support for Bilibili as it implements its own video summaries.
