### ISSUE TITLE
使用谷歌搜搜索的时候,页面能不能,不要强制滚动到到glarity的回答

### ISSUE THREAD

**Issue by thomasTAT** [sparticleinc/chatgpt-google-summary-extension#180]
**Describe the bug**
使用谷歌搜搜索的时候,页面能不能,不要强制跳转到glarity的回答. 我在看google generate ai的答案 😮‍💨

![演示視頻](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/109513632/96d4052f-1ab6-4cbb-a63e-69415f09b126)

- OS: Windows
- Browser edge
- Version 120.0.2210.91

**Comment by givebest** [comment]
可以把 Glarity 设为手动响应模式。

**Comment by givebest** [comment]
感谢反馈，最新版已修复。
