### ISSUE TITLE
京东页面，切换商品之后，页面会滚动到商品评价位置

### ISSUE THREAD

**Issue by labmain** [sparticleinc/chatgpt-google-summary-extension#182]
**Describe the bug**

当开启glarity插件时，京东页面在加载过程中，会被跳转到商品评论区域。关闭插件则恢复正常。

见视频附件，首先关闭了插件是正常的，开启插件之后，加载页面出现异常：  
[演示视频](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/13635026/deef0ccb-4ee5-485c-8c1c-ad74a88f29f5)

**Desktop (please complete the following information):**

- OS macOS
- Browser Chrome
- Version 120.0.6099.129

**Comment by givebest** [comment]
收到，下个版本修复一下
