### ISSUE TITLE
Why did you used fingerprint js in the code?

### ISSUE THREAD

**Issue by HakaishinShwet** [sparticleinc/chatgpt-google-summary-extension#185]
Do you track users who are using this addon/extension. Dev can you explain the purpose of using this in this addon because whoever has purchased the plan of glarity you can track them even without fingerprint js i believe from server and logs. so why use fingerprinting.

**Comment by givebest** [comment]
We use fingerprint js to create a unique ID for non-logged-in users.

**Comment by HakaishinShwet** [comment]
@givebest yeah i thought so but what is the use of making unique id of users who are not logged.And are there data send to somewhere like glarity server or somewhere. The reason i am asking is because you also know very well that this unique id with any tracking data can be sold to others and i havent seen full code yet but extension do have permissions of accessing urls and other data so if it is been send to server then it will hurt privacy for sure and thats why i wanted to know about it from you

**Comment by givebest** [comment]
Thanks for the feedback, we have removed the fingerprint js in the latest review version.
