### ISSUE TITLE
how to stop web page translate

### ISSUE THREAD

**Issue by cyrus123456** [sparticleinc/chatgpt-google-summary-extension#186]
**Describe the bug**

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- Version [e.g. 1.15.1]

**Comment by givebest** [comment]
<img width="933" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/8831c789-f3bf-4759-82d8-d6a80c281260">
Try cleaning up the website URL here.

**Comment by cyrus123456** [comment]
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/73327722/3002de15-1887-4cb4-beee-6408be86dde4)

i want turn off translation completely

**Comment by givebest** [comment]
<img width="679" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/3e5a3ce1-f94d-4480-8c8a-e2e1e98e8ec6">
<img width="536" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/ff347bed-3bdb-43b7-aa1f-7d655a770a93">
