### ISSUE TITLE
There will be a white bar in the top left corner of the webpage.

### ISSUE THREAD

**Issue by shanyan-wcx** [sparticleinc/chatgpt-google-summary-extension#187]
**Describe the bug**
There will be a white bar in the top left corner of the webpage, display as .glarity--selection__menu.notranslate
![屏幕截图 2024-01-14 150231](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/58252651/e4a39a33-7ef1-4d40-ac96-8ca9808d1de4)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [EDGE]
- Version [120.0.2210.133]

**Comment by givebest** [comment]
Thanks for the feedback, the latest version has been fixed.
