### ISSUE TITLE
azure openai的设置建议添加apiversion的配置

### ISSUE THREAD

**Issue by cl1107** [sparticleinc/chatgpt-google-summary-extension#188]
**Describe the bug**
目前使用api-version是2023-07-01-preview,目前请求会报错，建议更新到最新2023-12-01-preview或者增加一个配置项让用户自己配置

我有收到微软官方的邮件 
···
Update your code to use the latest Azure OpenAI Service preview API by 2 April 2024
You're receiving this email because you've used an older Azure OpenAI Service preview API in the last 30 days.

We recently made Azure OpenAI API [version 2023-12-01-preview](https://review.learn.microsoft.com/azure/ai-services/openai/api-version-deprecation?branch=pr-en-us-256331) available. You'll need to update any code that uses the following older versions before they're [retired](https://review.learn.microsoft.com/azure/ai-services/openai/api-version-deprecation?branch=pr-en-us-256331) on 2 April 2024:

2023-03-15-preview
2023-06-01-preview
2023-07-01-preview
2023-08-01-preview
2023-09-15-preview
The 2023-12-01 preview version includes improvements such as support for DALL-E 3.0 and enhanced content filtering.
# Required action

To avoid potential service disruptions, [update your code](https://learn.microsoft.com/azure/ai-services/openai/reference) that uses any of the retiring Azure OpenAI API versions to use version 2023-12-01 by 2 April 2024.

**Comment by givebest** [comment]
这周版本更新包括：
1. Azure API version 默认更新为：`2023-12-01-preview`;
2. Azure 增加自定义 API version 选项。


如果您有任何其他问题或需要进一步帮助，请随时与我们联系。感谢您的支持！
