### ISSUE TITLE
Auto refresh when middle-click Google search link

### ISSUE THREAD

**Issue by n374** [sparticleinc/chatgpt-google-summary-extension#189]
**Describe the bug**

> When i perform a Google search, Glarity display a summary at the right side of the webpage, as expected. However, when i middle-click on any search result, the clicked page opens in a new tab in the background, but the summary gets refresh, and the result is different from the previous one, as if it recreates the summary
> This problem also occurs in Youtube when i middle-click a recommend video on the right side

**Desktop (please complete the following information):**

- OS: [e.g. Windows] 
- Browser [e.g. chrome, brave] 
- Version [e.g. 1.15.1] 

|      | Desktop | Laptop |
| ----------- | ----------- | ----------- |
| OS      | macOS 13.2.1 (22D68)       | macOS 14.2.1 (23C71) |
| Browser   | Chrome Version 120.0.6099.216 (Official Build) (x86_64)        | Chrome Version 120.0.6099.199 (Official Build) (arm64)
| Version |  v4.18 | v4.18 |

**Comment by givebest** [comment]
Thanks for your feedback, this issue will be fixed in a new release this week.

**Comment by givebest** [comment]
Thanks for the feedback, the latest version has been fixed.
