### ISSUE TITLE
Random white line at the top left of websites that is being caused by the extension

### ISSUE THREAD

**Issue by ItzWilbert** [sparticleinc/chatgpt-google-summary-extension#190]
**Describe the bug**
Random white line at the top left of websites that is being caused by the extension

**Desktop (please complete the following information):**

- MacOS
- Chrome
- Version 120.0.6099.234 (Official Build) (arm64)

<img width="101" alt="Screenshot 2024-01-16 at 9 38 38 PM" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/40128654/2d11099f-03c7-4b4c-8a42-45b048c35d92">

<img width="59" alt="Screenshot 2024-01-16 at 9 39 06 PM" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/40128654/8f9fd13c-9103-44be-a5fc-f5102e07def8">

<img width="183" alt="Screenshot 2024-01-16 at 9 39 23 PM" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/40128654/cc094f5f-d786-4524-858c-251999c4132c">

**Comment by givebest** [comment]
Thanks for the feedback, this issue has been fixed in the new version this week.
