### ISSUE TITLE
"How to completely cancel this annoying floating window;"；怎样彻底取消掉这个 烦人的悬浮窗；

### ISSUE THREAD

**Issue by AShanWang** [sparticleinc/chatgpt-google-summary-extension#197]
To close the floating window, you need to click on the X number every time, which is very troublesome.
If you open a web page, you have to click on the X number for each web page.
Please tell me how to turn it off completely. I've looked through the settings and can't find the relevant settings.

I use this plugin often, but this floating window really blocks my vision.

As shown below:
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/129077870/e9989252-1198-4500-b16c-7f2ad92ab874)

---
要关闭悬浮窗，需要每次点击X号，很麻烦，
如果打开网页，还得每个网页分别点击X号。
请问怎样彻底关闭，我在设置里翻了个遍都不到相关设置。

我经常使用这个插件，但这个悬浮窗真的让我感到很阻挡视觉。

**Comment by givebest** [comment]
<img width="918" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/9993caa6-8332-46b8-b690-62326bb605fc">

感谢反馈，可以在选项里直接关闭，或者在黑名单里设置需要关闭的网站。

**Comment by AShanWang** [comment]
哦，天呐，
这个开关竟然在这，
我通过问AI，查google都没有找到，原来在这儿。

问题已解决，
非常感谢您的回复。

祝好！
