### ISSUE TITLE
Feature suggestion: Trigger Mode and prompt personalization.

### ISSUE THREAD

**Issue by nightkall** [sparticleinc/chatgpt-google-summary-extension#2]
First, Thanks for the extension It's the best GPT extension for Google and Youtube so far. I can now uninstall '[WebChatGPT](https://github.com/qunash/chatgpt-advanced)', '[ChatGPT for Google](https://github.com/wong2/chatgpt-google-extension)' and '[YouTube Summary with ChatGPT](https://chrome.google.com/webstore/detail/youtube-summary-with-chat/nmmicjeknamkfloonkhhcjmomieiodli/)'. 

Feature suggestion: 

- An option to activate the response with a click or a keyword in the search like '**Trigger Mode**' in 'ChatGPT for Google', so we **don't abuse the ChatGPT service** in searches where we don't need it. https://i.imgur.com/IClx8x6.png
- An option to **personalize the prompt** [like in here](https://i.imgur.com/eVFOEKg.jpg). Examples: 'Summarize the following in 5 bullet points:', 'Make an executive summary of the following:', 'Make a short summary of the following'...

**Comment by givebest** [comment]
Thank you very much for the tips and suggestions.
* The manual trigger option has been added.[1](https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/2311e6b25699c89ec15ef5814b315698519cbeeb)
* YouTube Custom Prompt has been added. [2](https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/79a86af2dc7aec683e4c118026f90a117f2a93af)

However, it needs to be approved by the Chrome WebStore to work, or you can try installing it manually: [https://github.com/sparticleinc/chatgpt-google-summary-extension#build-from-source](https://github.com/sparticleinc/chatgpt-google-summary-extension#build-from-source)

**Comment by givebest** [comment]
@nightkall The latest version has been reviewed and can be added for use here: [https://chrome.google.com/webstore/detail/glarity-summary-for-googl/cmnlolelipjlhfkhpohphpedmkfbobjc](https://chrome.google.com/webstore/detail/glarity-summary-for-googl/cmnlolelipjlhfkhpohphpedmkfbobjc)

**Comment by nightkall** [comment]
Thank you very much!  Here is the prompt I use to summarize Youtube videos:

```
Your output should use the following template:
### Summary
### Facts
- [Emoji] Bulletpoint

Your task is to summarize the text I give you in up to seven concise bullet points and start with a short, high-quality summary. Pick a suitable emoji for every bullet point. Use the following text: {{Transcript}}.
```
And the summary of [this video](https://www.youtube.com/watch?v=aGBLRlLe7X8) looks [like this.](https://i.imgur.com/WHtuhGy.jpeg) It's adapted from the prompt of [this extension](https://chrome.google.com/webstore/detail/chatgpt-suite-summarize-e/cbgecfllfhmmnknmamkejadjmnmpfjmp).

I hope you find it useful.

**Comment by givebest** [comment]
Thanks, this Prompt is great!
