### ISSUE TITLE
已设置为手动触发但右键“使用Google搜索”后搜索页会自动总结

### ISSUE THREAD

**Issue by ccsen** [sparticleinc/chatgpt-google-summary-extension#205]
触发模式为手动。
但是使用谷歌搜索有时会自动触发总结。而且在搜索页面重新点击搜索键，自动总结仍然会触发。
目前可复现的流程是：
1.选中网页文本，右键“使用Google搜索”
2.此时搜索页会自动触发总结

**Comment by givebest** [comment]
收到，我们排查一下。
