### ISSUE TITLE
利用反代，自建token转api，请问host该如何设置？

### ISSUE THREAD

**Issue by justincnn** [sparticleinc/chatgpt-google-summary-extension#208]
我在bob，和沉浸式翻译都是用自建的反代：ip/imitate/v1/chat/completions，然后把api key填写token，可以正常使用，

但是这个项目里无法生效，请问是否有设置的办法，谢谢

**Comment by givebest** [comment]
<img width="552" alt="image" src="https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/3918120/e78bc90b-f4df-4ec7-84e1-dcff00888624">这样试下呢

**Comment by justincnn** [comment]
谢谢反馈，我的safari设置里面找不到api path的设置，入下图：
![](https://s2.loli.net/2024/04/28/UlfBpq64wXQxbHc.png)

**Comment by givebest** [comment]
Safari 最新版还没通过审核，可以先用 Chrome 体验最新版本。

**Comment by justincnn** [comment]
> Safari 最新版还没通过审核，可以先用 Chrome 体验最新版本。

谢谢，chrome的已经在用了，主要是safari为主力，继续等待safari插件的上架：）

**Comment by justincnn** [comment]
> Safari 最新版还没通过审核，可以先用 Chrome 体验最新版本。

你好，在ios的插件设置里面有看到你上图的设置选项，但是mac端的看不到，请问下这个是不是和审核没关系？

![](https://s2.loli.net/2024/04/29/VfERHZwhT9eMtOy.png)

**Comment by givebest** [comment]
macOS/iOS是两个平台需要单独审核。

**Comment by folkevil** [comment]
> <img alt="image" width="552" src="https://private-user-images.githubusercontent.com/3918120/326222308-e78bc90b-f4df-4ec7-84e1-dcff00888624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTgzMDgsIm5iZiI6MTcxNDYxODAwOCwicGF0aCI6Ii8zOTE4MTIwLzMyNjIyMjMwOC1lNzhiYzkwYi1mNGRmLTRlYzctODRlMS1kY2ZmMDA4ODg2MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMDI0NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmExYmZiMTA0OGM5ZGUzZjRlZTQyODNlNzRmMTY0NDhiYWU4Y2NlN2E3Y2ZmMTI2ZDVlZjVmZmZjYzA2OWI5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.64j-g_LuMez6BNmJb-D11wj2-ehSy0OxOxCrdn9Bm64">Try it this way

Where I can find this option? I cloned repo and run it, but I got error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')
    at _r.PM [as constructor] (options.js:194:11849)
    at _r.xC [as render] (options.js:1:9220)
    at Ju (options.js:1:6879)
    at dl (options.js:1:2069)`

**Comment by WilliamDuTrendMicro** [comment]
I have the simialr issue ,how to debug it when pop the error message?
it works in the 沉浸式翻译 ,but not in the Glarity .
:
![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/55935318/fbe481d0-2242-44bd-947f-b965cb0f5aa0)
