### ISSUE TITLE
youtube账号视频记录问题

### ISSUE THREAD

**Issue by ttyy33** [sparticleinc/chatgpt-google-summary-extension#209]
**Describe the bug**

在登录youtbe账号观看视频，每次观看完一个视频youtube都有一个记录代表我看过这个视频，自从装了Glarity插件后，这个记录观看过哪些视频的功能就彻底不能用了，除非禁用Glarity插件，记录视频观看的功能才正常。

- OS: [Windows]
- Browser [chrome]
- Version [v4.17.11]

**Comment by givebest** [comment]
我们试了下，没能复现这个问题，麻烦升级最新版试试看。
