### ISSUE TITLE
After installing the browser extension, the formatting of tables on certain websites appears to be anomalous

### ISSUE THREAD

**Issue by lorrylockie** [sparticleinc/chatgpt-google-summary-extension#21]
dannymarsh@mjkey.net
"Thank you for developing this highly convenient plugin. However, I have observed certain anomalies. I have noticed that the plugin automatically adds styles to the page, which impacts the display of other regular websites that I visit.

Is it feasible to implement a whitelist feature to restrict the plugin's effects to specific websites only? This would minimize its impact on other websites within the browser."

**Comment by givebest** [comment]
Thank you for your advice.
I need to know these sites and then fix them.

Or try the following:

### Add or remove access to a specific site

1. On your computer, open Chrome.
2. At the top right, click More ![More](https://lh3.googleusercontent.com/E2q6Vj9j60Dw0Z6NZFEx5vSB9yoZJp7C8suuvQXVA_2weMCXstGD7JEvNrzX3wuQrPtL=w36-h36) ![and then](https://lh3.googleusercontent.com/QbWcYKta5vh_4-OgUeFmK-JOB0YgLLoGh69P478nE6mKdfpWQniiBabjF7FVoCVXI0g=h36) **More tools** ![and then](https://lh3.googleusercontent.com/QbWcYKta5vh_4-OgUeFmK-JOB0YgLLoGh69P478nE6mKdfpWQniiBabjF7FVoCVXI0g=h36) **Extensions**.
3. On the extension, click **Details**.
4. Under “Permissions,” add or remove a site:
   - **Add:** To the right of “Allowed sites,” click **Add**.
   - If you don’t see this option, change “Allow this extension to read and change all your data on websites you visit” to **On specific sites**.
   - **Remove:** To the right of the site, tap More ![More](https://lh3.googleusercontent.com/E2q6Vj9j60Dw0Z6NZFEx5vSB9yoZJp7C8suuvQXVA_2weMCXstGD7JEvNrzX3wuQrPtL=w36-h36) ![and then](https://lh3.googleusercontent.com/QbWcYKta5vh_4-OgUeFmK-JOB0YgLLoGh69P478nE6mKdfpWQniiBabjF7FVoCVXI0g=h36) **Remove**.[1](https://support.google.com/chrome_webstore/answer/2664769?visit_id=638137022585098716-1120374114&p=enable_extensions&rd=1&hl=en#)

**Comment by givebest** [comment]
Thank you for your feedback.

I have fixed the issue.

Now you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/future/packages) and adding it manually (https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome).
