### ISSUE TITLE
How do i delete my account

### ISSUE THREAD

**Issue by leotsaiCode** [sparticleinc/chatgpt-google-summary-extension#211]
**Describe the bug**

- OS: Windows
- Browser chrome
- Version 

Hi, I use google auth to login felo search, but I don't want to use this login method anymore, is there any solution to delete my account(google auth), use normal way to login (Email,password) ?

**Comment by givebest** [comment]
You can delete the account here https://account.felo.ai/account/security.

**Comment by leotsaiCode** [comment]
> You can delete the account here https://account.felo.ai/account/security.

It work, thanks!
