### ISSUE TITLE
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gpt-3.5-turbo-16k:streamGenerateContent?alt=sse: [404 ] models/gpt-3.5-turbo-16k is not found for API version v1, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods.

### ISSUE THREAD

**Issue by cyrus123456** [sparticleinc/chatgpt-google-summary-extension#212]
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gpt-3.5-turbo-16k:streamGenerateContent?alt=sse: [404 ] models/gpt-3.5-turbo-16k is not found for API version v1, or is not supported for StreamGenerateContent. Call ListModels to see the list of available models and their supported methods.

**Describe the bug**

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- Version [e.g. 1.15.1]

**Comment by givebest** [comment]
Try using the Google Gemini API configuration. If you want to use the gpt-3.5-turbo-16k model, you'll need to set up OpenAI.
