### ISSUE TITLE
知乎评论层会被自动触发显示

### ISSUE THREAD

**Issue by loveshizuka** [sparticleinc/chatgpt-google-summary-extension#213]
**Describe the bug**

Glarity会触发知乎问答页面的评论层自动打开。

例如：https://www.zhihu.com/question/433621605/answer/1618283949
- 当Glarity扩展激活时，打开以上的知乎页面，知乎的评论层会被自动激活显示。
- 当在以上的知乎页面时，点击Glarity图标激活扩展的侧栏时，知乎的评论层同样会被自动激活显示。

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 125.0.6422.142

**Comment by givebest** [comment]
感谢反馈，我们修复一下。
