### ISSUE TITLE
No keymoments when not using official glarity api?

### ISSUE THREAD

**Issue by zjplab** [sparticleinc/chatgpt-google-summary-extension#214]
**Describe the bug**

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- Version [e.g. 1.15.1]

**Comment by givebest** [comment]
Please upgrade to the latest V4 version. You can also use your OpenAI API Key to check key moments.

**Comment by givebest** [comment]
Please upgrade to the latest V4 version. You can also use your OpenAI API Key to check key moments.
