### ISSUE TITLE
v4.0+版本的下载包

### ISSUE THREAD

**Issue by canvs** [sparticleinc/chatgpt-google-summary-extension#215]
**Describe the bug**
github的插件包还是3.0+的 4.0+的包可以提供下么？因为使用rpa工具无法在线只能本地安装

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome, brave]
- Version [e.g. 1.15.1]

**Comment by kele527** [comment]
我本地构建出来还是1.7的版本，你知道3.0+的源码在哪里吗？

**Comment by canvs** [comment]
> 我本地构建出来还是1.7的版本，你知道3.0+的源码在哪里吗？

package目录里有

**Comment by givebest** [comment]
感谢支持，v4最新版本已放到这里：https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/main/packages/chromium-chrome.zip
