### ISSUE TITLE
为什么我按照文档本地构建后，版本是1.7.0？

### ISSUE THREAD

**Issue by kele527** [sparticleinc/chatgpt-google-summary-extension#216]
**Describe the bug**
我拉取代码本地build后，chrome安装插件，显示版本是1.7.0
但是在package目录看到有一个压缩包，打开是3.x版本，但是不是源码，不知道3.x版本的源码是在哪里？

![image](https://github.com/sparticleinc/chatgpt-google-summary-extension/assets/345445/0a8e3c87-5408-4131-b663-a375a0f0e7d0)

**Comment by hellozhangran** [comment]
新版本应该没有开源

**Comment by givebest** [comment]
抱歉，2.0 开始重构了代码，目前公司暂未考虑开源。
