### ISSUE TITLE
Translation of answers in the language

### ISSUE THREAD

**Issue by Zizlik** [sparticleinc/chatgpt-google-summary-extension#218]
**Describe the bug**
Even though I've modified each individual promt for all kinds of functions, it always outputs in the original selected language. So even though I have written in the prompts "always write the text in Czech" or the entire promt is written in Czech, it still displays the output in English.  Isn't it possible to add more options to select from Language (Czech or Polish, for example)?

**Desktop information:**
- OS: Windows
- Browser: Edge and chrome
- Version: 4.30.21

**Comment by wangzhiming1999** [comment]
You can try to change the browser language to Polish and then select the output language to automatic
![image](https://github.com/user-attachments/assets/d4f680c7-9d0a-4266-8486-1965b851e6b5)

**Comment by givebest** [comment]
Thanks for the feedback! The latest version now includes Polish.
