### ISSUE TITLE
Background turn dark

### ISSUE THREAD

**Issue by iscoler** [sparticleinc/chatgpt-google-summary-extension#220]
**Describe the bug**
https://steimelchrome.github.io/document-pip/user-gesture.html
When enable Glarity in Chrome,  all the website turn dark, such as the above website.

**Desktop (please complete the following information):**

- OS: MacOS Sonoma 14.5
- Browser: Chrome
- Version: 127.0.6533.120 (Official Build) (arm64)

**Comment by givebest** [comment]
qThanks for the feedback, we've fixed it and submitted it for review.

**Comment by forrany** [comment]
The same here, the css style polluted global style
