### ISSUE TITLE
user quota is not enough

### ISSUE THREAD

**Issue by pnedfff** [sparticleinc/chatgpt-google-summary-extension#222]
**Describe the bug**
{"error":{"message":"user quota is not enough (request id: 20240909152207513198801NCNrvKxv)","type":"new_api_error","param":"","code":"insufficient_user_quota"}}
**Desktop :**

- OS: MacOS
- Browser:  [Chrome]
- Version:  128.0.6613.120（正式版本）
![image](https://github.com/user-attachments/assets/ef97c8da-5dbb-4704-9bc4-6898dbc867f9)

**Comment by wangzhiming1999** [comment]
We didn't set this error to this effect, but the reason for this error is that your custom interface quota is insufficient
