### ISSUE TITLE
The plugin causes the page to crash when processing longer Youtube videos

### ISSUE THREAD

**Issue by MaxnSter** [sparticleinc/chatgpt-google-summary-extension#24]
**Describe the bug**
Even when set to manually trigger mode, the extension crashes while accessing YouTube videos that are longer due to the large amount of text.

example video : https://www.youtube.com/watch?v=AmGSEH7QcDg

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome

**Comment by givebest** [comment]
I have fixed this issue
Now you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages) and adding it manually (https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome).
