### ISSUE TITLE
Request for adding support for PubMed

### ISSUE THREAD

**Issue by goldengrape** [sparticleinc/chatgpt-google-summary-extension#3]
Hi there,

First of all, I want to thank you for creating this amazing tool. I have been using it for a while and found it to be very helpful. I would like to request adding support for PubMed.

PubMed is a great resource for finding medical literature. It is often referred to as the Google of medical literature. One of the unique features of PubMed is that it provides a summary or abstract of the content of each article. Additionally, some of the articles on PubMed have the full text available. If it were possible to use ChatGPT to read and interpret the full text of these articles, it would be a valuable tool for researchers and medical professionals.

I understand that adding support for PubMed would require additional development time and effort. However, I believe that it would be a great addition to the tool, and it would benefit a lot of users.

Thank you for considering my request.

Best regards,

**Comment by givebest** [comment]
Does it look like this([Screenshots](https://imgur.com/PW7XbOz))?
 If so, you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/future/packages) and adding it manually ([https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome](https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome)).

**Comment by goldengrape** [comment]
Great!!!
Now that I can summarize on the summary page, can you add this feature to the full text page as well?
For example https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8083117/

**Comment by givebest** [comment]
I have added this feature.
Now you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/future/packages) and adding it manually (https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome).
