### ISSUE TITLE
Feature Request: Timestamp Functionality for Summary Video Plugin

### ISSUE THREAD

**Issue by epodak** [sparticleinc/chatgpt-google-summary-extension#35]
I hope this message finds you well. I wanted to reach out and request a new feature for the summary video plugin. I think it would be incredibly useful if the plugin had a timestamp functionality that allowed users to easily jump to specific moments in the video.

As you know, the plugin is great for summarizing long videos, but it can be difficult to find specific moments within the video without scrolling through the entire summary. By adding a timestamp functionality, users could simply click on a timestamp link and be taken directly to the corresponding moment in the video.

I believe this feature would make the plugin even more user-friendly and improve the overall user experience. If this is something that could be implemented, I would greatly appreciate it!

Thank you for your time and consideration.

**Comment by givebest** [comment]
Thanks for the suggestion, you can try this Beta version: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
