### ISSUE TITLE
Can not Select Models

### ISSUE THREAD

**Issue by mengxingshike2012** [sparticleinc/chatgpt-google-summary-extension#39]
**Describe the bug**
After the version, I can not select the models

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]

<img width="486" alt="image" src="https://user-images.githubusercontent.com/4207708/223910049-69b5636e-baa5-462b-a0b4-db8fba6b2e81.png">

**Comment by givebest** [comment]
Sorry, this is a serious bug. we have fixed it but it needs to be reviewed and approved.

Now you can try to remove the plugin and reinstall it. Or you can try downloading the experience package (https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/main/packages) and adding it manually (https://github.com/sparticleinc/chatgpt-google-summary-extension#chrome).

**Comment by mengxingshike2012** [comment]
Thanks , I have removed and reinstalled it. It works now. Thanks.
