### ISSUE TITLE
Maybe we need a custom output template setting?

### ISSUE THREAD

**Issue by boholder** [sparticleinc/chatgpt-google-summary-extension#4]
Hey, thanks for this nice extension! 
I have experimented with several Youtube videos and found that all summaries contain a lot of emoji, which I guess is the effect of [this line of code](https://github.com/sparticleinc/chatgpt-google-summary-extension/blob/1886beddee9005bd138cfd32d7ca92652134b50c/src/utils.ts#L19).
Although emoji would make the replies more vivid, unfortunately most of the emoji generated by ChatGPT have little relevance to the text, which affects the understanding to the summaries.

I guess if we allow users to set their own reply style, or pre-set several styles for users to choose, the user experience will be improved a little bit?

(I'm not familiar with front-end development, so I just deleted the emoji and re-built it. I think it would be better if the settings screen had a corresponding settings text box?)

**Comment by givebest** [comment]
Thanks for the suggestion. You can change the default Prompt for YouTube via Options.
