### ISSUE TITLE
Feature Request:  hope to support Safari.

### ISSUE THREAD

**Issue by notHide** [sparticleinc/chatgpt-google-summary-extension#45]
Safari on iOS also supports plugins. I hope that this plugin can also support Safari on Mac/iOS, so that it can be used on both platforms. 
Looking forward to it.

**Comment by givebest** [comment]
We have initially implemented Safari/iOS Safari support, try here: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/safari/Glarity

**Comment by givebest** [comment]
For duplicate issues, see here: #51
