### ISSUE TITLE
Add a button where we click and choose which language we want to translate summary

### ISSUE THREAD

**Issue by ghost** [sparticleinc/chatgpt-google-summary-extension#46]
It will be good if we see a button where we click and choose language  from many like 100+ languages to translate summary to others languages, and that translation if also done through ChatGPT will be awesome

NOTE: i am not talking about this option `The language used in ChatGPT response. Auto is recommended.` but its also good if you add many more languages to it not just some

**Comment by MiracleXYZ** [comment]
+1 for this. It would be really useful to have the option to view summaries in different languages, either by translating them or generating a new summary in the desired language.

**Comment by givebest** [comment]
Try it out and now support summary content translation: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
