### ISSUE TITLE
Feature Request: Edit the prompt for search

### ISSUE THREAD

**Issue by AsafMah** [sparticleinc/chatgpt-google-summary-extension#48]
Editing the prompt for youtube is really cool, I think having control of the prompt for searching would be great too.

**Comment by TwilightHome** [comment]
Indeed, that would be very useful.

**Comment by givebest** [comment]
Thank you for the suggestion to try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
