### ISSUE TITLE
Include newest gpt-3.5-turbo 10X cheaper model

### ISSUE THREAD

**Issue by Flizyx** [sparticleinc/chatgpt-google-summary-extension#50]
Currently selecting "gpt-3.5-turbo" runs gpt-3.5-turbo-0301
not the gpt-3.5-turbo cheap model, which costs a lot less

**Desktop:**

 - OS:  Windows
 - Browser chrome, brave

**Comment by givebest** [comment]
Sorry, I haven't found the documentation for switching gpt-3.5-turbo/gpt-3.5-turbo-0301 model. Can you help me?

**Comment by nickwzy** [comment]
https://community.openai.com/t/attempting-to-use-gpt-3-5-turbo-getting-gpt-3-5-turbo-0301-instead/94411/2

**Comment by givebest** [comment]
@Flizyx https://www.reddit.com/r/OpenAI/comments/11mrdz8/model_usage_says_gpt35turbo0301_but_api_call_uses/
