### ISSUE TITLE
[Feature request] Support for Safari?

### ISSUE THREAD

**Issue by yihuanlin** [sparticleinc/chatgpt-google-summary-extension#51]
Thank you for your work. 
This extension works very well on Edge for macOS. It would be more than great if it also works for Safari.

**Comment by yihuanlin** [comment]
UPDATE: I tried to convert it to safari extension but it says "open_in_tab" is not supported in Safari
`xcrun safari-web-extension-converter /Users/Home/Library/Application\ Support/Microsoft\ Edge\ Dev/Default/Extensions/cmnlolelipjlhfkhpohphpedmkfbobjc/1.1.7_0`

```
App Name: Glarity-Summary for Google/YouTube (ChatGPT)
App Bundle Identifier: com.yourCompany.Glarity-Summary-for-Google-YouTube--ChatGPT-
Platform: All
Language: Swift
Warning: The following keys in your manifest.json are not supported by your current version of Safari. If these are critical to your extension, you should review your code to see if you need to make changes to support Safari:
	open_in_tab
Unable to add extension files to project.
```

**Comment by givebest** [comment]
@yihuanlin  

We have initially implemented Safari/iOS Safari support, try here: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/safari/Glarity

**Comment by givebest** [comment]
@edr1412 

You can try to build and use, see: https://developer.apple.com/documentation/safariservices/safari_web_extensions/running_your_safari_web_extension

**Comment by givebest** [comment]
🎉🎉 App Store review approved. https://apps.apple.com/cn/app/glarity/id6446609868?mt=12
