### ISSUE TITLE
Feature request: Summarize any page.

### ISSUE THREAD

**Issue by nightkall** [sparticleinc/chatgpt-google-summary-extension#55]
Thanks for your work!

I have a feature suggestion: It would be great if there was an option to **generate a summary of any web article** with just one click using the extension toolbar button or through the context menu.

Thank you!"

**Comment by givebest** [comment]
Thank you for your suggestion, we are working on this feature. It is planned to be submitted for review this week.

**Comment by MartinXM** [comment]
The request here. It would be nice for it to work on github issue page.

**Comment by givebest** [comment]
@nightkall 

Now you can try the manual installation experience: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

**Comment by givebest** [comment]
@kazekatze 
Thank you for the suggestion, please try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

**Comment by n0madic** [comment]
Is it possible to make the summary button on the pages floating as it sometimes covers the content, or else to make the dialog open only by clicking on the extension button?

**Comment by givebest** [comment]
> Is it possible to make the summary button on the pages floating as it sometimes covers the content, or else to make the dialog open only by clicking on the extension button?

The Glarity icon can be turned off in options.

**Comment by n0madic** [comment]
where exactly? I didn't find it in the options... 
v1.5.0 beta

**Comment by givebest** [comment]
> where exactly? I didn't find it in the options...
> v1.5.0 beta

Click on the icon or extension icon on the right side of the page.

**Comment by givebest** [comment]
> where exactly? I didn't find it in the options... 
> 
> v1.5.0 beta

Click on the icon on the right side of the page, or expand the icon.
