### ISSUE TITLE
Can't Auto delete conversations generated by search

### ISSUE THREAD

**Issue by linonetwo** [sparticleinc/chatgpt-google-summary-extension#56]
**Describe the bug**

This can't be toggled 
![截屏2023-03-15 10 53 35](https://user-images.githubusercontent.com/3746270/225193064-712460bc-7075-49cb-9e74-cd89e769c1bc.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by coranholmes** [comment]
I have encountered the same issue.
