### ISSUE TITLE
Feature Request: Support bilibili (www.bilibili.com)

### ISSUE THREAD

**Issue by shanyan-wcx** [sparticleinc/chatgpt-google-summary-extension#58]
This is also a video website with a large number of users.

**Comment by YanMu2020** [comment]
OpenAI has been blocked by the Great Firewall, and accessing Bilibili using a proxy can be very slow.
openai已经被墙了，而用代理的方式访问bilibili网络会很卡顿

**Comment by shanyan-wcx** [comment]
> OpenAI has been blocked by the Great Firewall, and accessing Bilibili using a proxy can be very slow.  openai已经被墙了，而用代理的方式访问bilibili网络会很卡顿

If you use Clash to proxy with rule-based routing, it won't be slow.

**Comment by givebest** [comment]
@shanyan-wcx YouTube in summary relies on transcript, I found that most of the bilibili videos do not have transcript.

**Comment by YanMu2020** [comment]
> > OpenAI has been blocked by the Great Firewall, and accessing Bilibili using a proxy can be very slow.  openai已经被墙了，而用代理的方式访问bilibili网络会很卡顿
> 
> If you use Clash to proxy with rule-based routing, it won't be slow.

I added a whitelist on SwitchyOmega.

**Comment by shanyan-wcx** [comment]
> 



> @shanyan-wcx YouTube in summary relies on transcript, I found that most of the bilibili videos do not have transcript. 
比较新的视频没有字幕，老视频基本都有自动生成的字幕了。

**Comment by givebest** [comment]
Now bilibili video summary is supported, but it is not ideal because there are too few bilibili videos that support transcription (not subtitles synthesized within the video). You can experience the beta version here： https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

**Comment by shanyan-wcx** [comment]
It looks good, but it would be even better if you could move it under the uploader information and modify the appearance.
![屏幕截图 2023-03-21 175739](https://user-images.githubusercontent.com/58252651/226575827-657f302f-ec88-449a-8c89-391fe258fa2c.png)

**Comment by shanyan-wcx** [comment]
In addition, in widescreen mode, it should be moved below the video.@givebest
![网页捕获_21-3-2023_18391_www bilibili com](https://user-images.githubusercontent.com/58252651/226583694-f698bd15-fc9e-4831-9535-d4ee5d0c56a3.jpeg)

**Comment by givebest** [comment]
Please try again.
