### ISSUE TITLE
keep the GPT summary dialog box stay still

### ISSUE THREAD

**Issue by goldengrape** [sparticleinc/chatgpt-google-summary-extension#60]
Can the GPT summary  dialog box be opened with enough space at once, or can the height of the dialog box be locked, and a scrollbar is used when it exceeds its limit? Currently, the height of the dialog box keeps increasing, causing webpage links below it to constantly move.

If you want to click on a button or link, you have to wait for GPT to finish speaking.

**Comment by givebest** [comment]
Thank you for the suggestion to try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
