### ISSUE TITLE
Glarity is causing javascript error on every other website

### ISSUE THREAD

**Issue by reorx** [sparticleinc/chatgpt-google-summary-extension#61]
**Describe the bug**
Glarity is causing javascript error on every other website that is not in the supported site list, including but not limited to:
- https://news.ycombinator.com/
- https://www.producthunt.com/
- https://threadreaderapp.com/

![image](https://user-images.githubusercontent.com/405972/228454870-0d6c29ed-23fe-4d32-aab5-9798db586340.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

---

You are injecting content script on every website
```
   "content_scripts": [ {
      "css": [ "content-script.css" ],
      "js": [ "content-script.js" ],
      "matches": [ "\u003Call_urls>", "*://*/*" ]
   } ],
```

This is understandable because the websites Glarity supports are extensible, and matching sites in the manifest is too much hassle.

But you should enhance the code to change irrelevant pages as little as possible. I believe this error is caused by not checking whether the site is in the supported site list and assuming something should be there to proceed.

Also, I think you should avoid injecting css this way. It's uncontrollable, you should let the content-script.js inject the css after checking it is a supported site.

**Comment by givebest** [comment]
@reorx Please tell me which version you are using.

**Comment by givebest** [comment]
Sorry, you can try our beta version, which fixes this issue and adds many new features. https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
