### ISSUE TITLE
Feature Request: Customize the url of the openai api

### ISSUE THREAD

**Issue by shanyan-wcx** [sparticleinc/chatgpt-google-summary-extension#62]
So that I can change the proxy URL myself.

**Comment by numbbbbb** [comment]
+1 on this, shouldn't be too hard to support but it's a huge improvement for users.

**Comment by givebest** [comment]
@shanyan-wcx @numbbbbb  
Try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
