### ISSUE TITLE
The github summary is too long and contains unnecessary content

### ISSUE THREAD

**Issue by shanyan-wcx** [sparticleinc/chatgpt-google-summary-extension#63]
It should only summarize the introduction, functions, features, etc., and should not include specific content such as installation methods, download addresses, etc.
![屏幕截图 2023-03-31 125409](https://user-images.githubusercontent.com/58252651/229026156-7c69f01a-ab6e-4ee5-9a5e-ce3942ba51e1.png)

**Comment by givebest** [comment]
Try it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
