### ISSUE TITLE
[Feature Request] Add Hotkey to on/off extension

### ISSUE THREAD

**Issue by jellydn** [sparticleinc/chatgpt-google-summary-extension#64]
# Feature Request

### Summary

- Add hotkey for on/off extension

### Motivation

- The toggle setting is quite good however it might cause some issue with JS error when injecting HTML/JS/CSS. So I think that's a safe approach if it has hotkey on/off

### Proposed Solution

- For example, https://chathub.gg has similar hotkey [CMD + J] to show the chat hub client.

### Additional Information

[Include any additional information or context that may be relevant to this feature request.]

### Related Issues and Pull Requests

#61 #11 #23 

Thank you for considering my feature request!

**Comment by wangzhiming1999** [comment]
最新版本提供了ctrl + M 的快捷方式
