### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by Enigma1309** [sparticleinc/chatgpt-google-summary-extension#65]
**Describe the bug**
Failed to load response from ChatGPT:
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
[Retry](javascript:void(0))
If this keeps happening, change AI provider to OpenAI API in the Extension option.

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser - brave

Screenshot

![image](https://user-images.githubusercontent.com/94917588/229794922-f86bb32e-d148-4c44-88a0-33f7d099e616.png)

**Comment by givebest** [comment]
The openAI api quota has run out.

**Comment by Enigma1309** [comment]
> The openAI api quota has run out.

What does that mean??and how can i fix it?

**Comment by givebest** [comment]
> > The openAI api quota has run out.
> 
> 
> 
> What does that mean??and how can i fix it?

Expired April 1, 2023。

**Comment by Enigma1309** [comment]
is it paid?
how can i get it for free?

**Comment by givebest** [comment]
> is it paid?
> 
> how can i get it for free?

Get a new account.
