### ISSUE TITLE
Will the Blacklist Sites support Regex or wildcard ?

### ISSUE THREAD

**Issue by thatscode** [sparticleinc/chatgpt-google-summary-extension#68]
**Function issue**
Hi there，will the `Blacklist Sites` URLs list  support Regex or wildcard ? 😁

I was trying to list a mount of urls of My Company in the `Blacklist`, they are regular with several domain suffixes.
So I am wondering that if there is a plan to support `Regex` or `wildcard` in the URLs list.

BTW: Thanks for your wonderful work.

**Comment by givebest** [comment]
We support this feature in Glarity 2.0.
