### ISSUE TITLE
add presearch.org 

### ISSUE THREAD

**Issue by Sergo1217** [sparticleinc/chatgpt-google-summary-extension#69]
add presearch.org to the list of search engines

**Comment by givebest** [comment]
Thanks for the suggestion, try it. https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

<img width="949" alt="presearch" src="https://user-images.githubusercontent.com/3918120/231641925-e723bdbe-bd8e-414f-9e58-59c018aec056.png">
