### ISSUE TITLE
获得搜索结果后可直接开始聊天，可以添加这个（直接聊天）入口吗？

### ISSUE THREAD

**Issue by yangchen158158** [sparticleinc/chatgpt-google-summary-extension#73]
在搜索引擎结果中同时显示ChatGPT的回在搜索引擎结果中同时显示ChatGPT的回答。获得搜索结果后可直接开始聊天，可以添加这个（直接聊天）入口吗？答。获得搜索结果后可直接开始聊天，可以添加这个（直接聊天）入口吗？
类似这个https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf

**Comment by sundayYa** [comment]
我也有同样的需要

**Comment by givebest** [comment]
聊天窗口是进一步询问总结内容呢，还是直接进入聊天，与网页没有关联？

**Comment by thermalme** [comment]
> 聊天窗口是进一步询问总结内容呢，还是直接进入聊天，与网页没有关联？
我的需求是跟网页有关联，比如他总结了一篇文章，能不能继续问他一些细节让他回答或者拓展相关描述。

**Comment by givebest** [comment]
This feature is under development.

**Comment by givebest** [comment]
Glarity 2.0 is now supported and can be added to the Chrome web store.
