### ISSUE TITLE
[Feature]: Support specifying protocol for api host

### ISSUE THREAD

**Issue by cesaryuan** [sparticleinc/chatgpt-google-summary-extension#74]
I have deployed an OpenAI proxy service locally which listens on http://127.0.0.1:8000. However, there is no way to specify the protocol for the API host. I have tried typing `http://127.0.0.1:8000` in the API Host box, but it doesn't work.

![image](https://user-images.githubusercontent.com/35998162/232300416-28e9a6a8-5acf-4ef9-b7a1-18f5cbfceff3.png)

**Comment by givebest** [comment]
You need to configure it as https, then type 127.0.0.1:8000 and try it.

**Comment by cesaryuan** [comment]
> You need to configure it as https, then type 127.0.0.1:8000 and try it.

This is a workaround but will be prevented by the browser. 😂

![image](https://user-images.githubusercontent.com/35998162/232312335-41348d77-806f-41eb-aea3-97d58b915fbe.png)

**Comment by givebest** [comment]
Click on a blank page and type: this is unsafe

**Comment by cesaryuan** [comment]
Sorry, don't get it. Should I type the "this is unsafe" in the extension background page? 😳

**Comment by givebest** [comment]
Try ngrok.
