### ISSUE TITLE
Bigger box area for Glarity

### ISSUE THREAD

**Issue by eonsmile** [sparticleinc/chatgpt-google-summary-extension#76]
Anyway to increase the size (vertically) for the Glarity box (especially in context of using Youtube)?

**Comment by givebest** [comment]
Now that we have limited the height of the Glarity box, as increasing the height during the summary output will make the content below less clickable, do we need to manually adjust the Glarity box size?

**Comment by eonsmile** [comment]
Can this be a user input (with a default value)?

**Comment by givebest** [comment]
> Can this be a user input (with a default value)?

Good idea, we plan to make it happen.

**Comment by givebest** [comment]
@eonsmile 

Now you can try out this feature. https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages
![SCR-20230418-pzmt](https://user-images.githubusercontent.com/3918120/232748180-d17eee8f-0605-4beb-bda4-8770bbac949c.png)

**Comment by eonsmile** [comment]
Nice!  Super useful!

Also I can see that there is persistence of this setting ....
