### ISSUE TITLE
插件更新后只要选中文本就会弹出菜单，这个功能具有干扰性

### ISSUE THREAD

**Issue by demxiao** [sparticleinc/chatgpt-google-summary-extension#86]
如果不是Bug的话，我觉得选中文本就弹出菜单的效果非常有干扰性。
希望能够增加这个功能的开关选项。至少允许我关闭这个功能。

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Browser Thorimu

**Comment by ForsakenHZ** [comment]
+1

**Comment by ForsakenHZ** [comment]
Please allow me to disable the automatic pop-up after selecting text.

**Comment by givebest** [comment]
Sorry for the trouble, try the beta version to disable it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

**Comment by givebest** [comment]
You can now go to the Chrome Store and update to 1.15.1 to disable this feature.
