### ISSUE TITLE
Please allow me to disable the automatic pop-up after selecting text.

### ISSUE THREAD

**Issue by ForsakenHZ** [sparticleinc/chatgpt-google-summary-extension#87]
Please allow me to disable the automatic pop-up after selecting text.

**Comment by givebest** [comment]
Sorry for the trouble, try the beta version to disable it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

**Comment by Joseph7451797** [comment]
> Sorry for the trouble, try the beta version to disable it: https://github.com/sparticleinc/chatgpt-google-summary-extension/tree/beta/packages

Hi, thanks for building the convenient tool. Do you have a schedule for the release of this beta version?

**Comment by givebest** [comment]
@Joseph7451797 
This beta version (1.15.1) was submitted to the chrome store yesterday, now try adding it manually or using https://addons.mozilla.org/zh-CN/firefox/addon/glarity/ (1.15.1) on Firefox
