### ISSUE TITLE
Longer textbox

### ISSUE THREAD

**Issue by ed-ckh** [sparticleinc/chatgpt-google-summary-extension#88]
Hi,
Thanks a lot for this great extension. Really helpful on summarizing search results. Can I have a longer textbox? It would be more convenient to read.
Best regards,

**Comment by givebest** [comment]
You can try to adjust the right size here.
<img width="434" alt="SCR-20230427-mgqw" src="https://user-images.githubusercontent.com/3918120/234770062-5d677134-3f35-4fa1-a664-c6b3b50db648.png">

**Comment by ed-ckh** [comment]
Thanks a lot. It works fine for me. : )
