### ISSUE TITLE
Suggest adding custom API domain and custom API key.

### ISSUE THREAD

**Issue by nonplaybox** [sparticleinc/chatgpt-google-summary-extension#96]
Some users use the OpenAI key provided by Azure and cannot use it directly in this plugin. Therefore, it is necessary to customize a server for conversion. For details, please refer to the following project.
https://github.com/haibbo/cf-openai-azure-proxy

**Comment by givebest** [comment]
Is the setting not working here?
<img width="1040" alt="SCR-20230508-hzaw" src="https://user-images.githubusercontent.com/3918120/236710587-bccaba01-25a2-4401-9afb-1650777b283b.png">

**Comment by nonplaybox** [comment]
抱歉，我忘了提供以下信息：
我使用的是mac端的Safari，从App Store下载安装的该插件[Glarity]。
在我的设置页面，并没有自定义API HOST的功能。

**Comment by givebest** [comment]
Let's update the app store version so you can try the chrome web store version with this feature before it's approved.

**Comment by givebest** [comment]
Custom API host are now available in the App Store. 
https://apps.apple.com/cn/app/glarity/id6446609868?mt=12
